name: 'Forge Review-app Clean Action'
description: 'Clean a review-application on Laravel Forge'
author: 'rygilles'

branding:
  icon: upload-cloud
  color: red

inputs:
  forge_api_token:
    description: 'Laravel Forge API key'
    required: true
  forge_server_id:
    description: 'Laravel Forge server ID'
    required: true
  root_domain:
    description: 'Root domain under which to create review-app site'
    required: false
  host:
    description: 'Site host of the review-app'
    required: false
  prefix_with_pr_number:
    description: 'Use the pull-request number as host and database prefix when host is not manually defined'
    required: false
    default: 'true'
  fqdn_prefix:
    description: 'Prefix the whole FQDN (e.g.: "app.")'
    required: false
  pr_number:
    description: 'Manually define pull-request number'
    required: false
  database_name:
    description: 'Database name of the review-app site'
    required: false
  database_name_prefix:
    description: 'Database name prefix, useful for PostgreSQL that does not support digits (PR number) for first chars'

outputs:
  host:
    description: 'Host of the review-app (generated or forced one in inputs)'
    value: ${{ steps.forge-review-app-clean-action.outputs.host }}
  database_name:
    description: 'Database name of the review-app (generated or forced one in inputs)'
    value: ${{ steps.forge-review-app-clean-action.outputs.database_name }}

runs:
  using: 'composite'
  steps:
    - name: "Forge Review-app Clean Action"
      id: forge-review-app-clean-action
      uses: "docker://ghcr.io/web-id-fr/forge-review-app-clean-action:v1.1.2"
      env:
        INPUT_FORGE_API_TOKEN: ${{ inputs.forge_api_token }}
        INPUT_FORGE_SERVER_ID: ${{ inputs.forge_server_id }}
        INPUT_ROOT_DOMAIN: ${{ inputs.root_domain }}
        INPUT_HOST: ${{ inputs.host }}
        INPUT_PREFIX_WITH_PR_NUMBER: ${{ inputs.prefix_with_pr_number }}
        INPUT_FQDN_PREFIX: ${{ inputs.fqdn_prefix }}
        INPUT_PR_NUMBER: ${{ inputs.pr_number }}
        INPUT_DATABASE_NAME: ${{ inputs.database_name }}
        INPUT_DATABASE_NAME_PREFIX: ${{ inputs.database_name_prefix }}
